module.exports = {
  PREFIX: ""^"",
  SUBZERO-MD;;;BNULWAKJ#HY9NHHM7HHZTPNGKS-RBWQPM-H_AYDGRKFTE1F2FD24: "SUBZERO-MD;;;bNUlwAKJ#hY9NhHM7hHzTpngKs-rbWqpm-h_AYDGRkFtE1f2fd24",
  SESSION_ID: "default_session",
  OWNER_NUMBER: "1234567890",
};